#pragma once
#define PORT_STRING "29377"
#define MAX_MESSAGE_SIZE 512

#define STC_AUTH_REQUIRED 1
#define STC_UNREAD_COUNT 2
#define STC_POP_MESSAGE 3
#define STC_TARGET_NOT_FOUND 4
#define STC_NO_MESSAGES 5
#define STC_UNABLE_TO_POP 6
#define STC_SUCCESSFULLY_PUSHED 7
#define STC_UNABLE_TO_PUSH 8

#define CTS_AUTH -1
#define CTS_PUSH_MESSAGE -2
#define CTS_REQUEST_UNREAD -3
#define CTS_REQUEST_POP -4
